name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * 1"

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  
  test-e2e:
    name: Test Extension with Sunbeam
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Test with Sunbeam
        uses: actions/sbx_test_action@ef33283da1472599541ac0f2fa363b1ddf216a80
        with:
          sunbeam-version: 'dev'
          extension-name: 'Ulthran/sbx_demic'
          extension-branch-name: ${{ github.head_ref }}
          other-extensions: 'sunbeam-labs/sbx_coassembly'
          test-directory: '.tests'
