name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "0 13 * * 1"

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          VALIDATE_SNAKEMAKE_SNAKEFMT: true
  
  test-snakemake:
    name: Test Extension
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: setup-conda
        # You may pin to the exact commit or the version.
        # uses: s-weigand/setup-conda@945fd9e7c92f1efb12634ba552ee0b2ec140a5fd
        uses: s-weigand/setup-conda@v1.1.0
        with:
          # Additional channels like 'conda-forge' which can be used to install packages
          conda-channels: '' # optional, default is 
      
      - name: Install Dependencies
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        run: |
          python -m pip install -U pytest
          git clone https://github.com/sunbeam-labs/sunbeam sunbeam
          cd sunbeam
          bash install.sh -v
          git clone https://github.com/sunbeam-labs/sbx_coassembly/ extensions/sbx_coassembly
          if [ -z "${BRANCH_NAME}" ]
          then
            git clone https://github.com/Ulthran/sbx_demic/ extensions/sbx_demic
          else
            git clone -b $BRANCH_NAME https://github.com/Ulthran/sbx_demic/ extensions/sbx_demic
          fi

      - name: Run Tests
        run: |
          source activate sunbeam3
          pytest .tests/
